# Tema 04: Cinemática. Elementos para la descripción del movimiento. Movimientos de especial interés. Métodos para el estudios experimental del movimiento.

## Introducción 

La cinemática estudia el movimiento de los cuerpos, así como las leyes que rigen esos movimientos. En el estudio de la cinemática no se tienen en cuenta las causas que generan esos movimientos ni las dimensiones de los cuerpos sujetos a estudio, considerando estos como meros puntos. El método más apropiado para el estudio de la cinemática sería aquel que, empezando por los movimientos más sencillos, amplia poco a poco el estudio hacia movimientos más complejos. De esta forma se adquiere un conocimiento inductivo de los mismo , permitiendo analizar cualquier movimiento como una composición de movimientos más sencillos.

El ámbito de la cinemática aborda situaciones tanto estáticas como dinámicas, en función de las fuerzas a las que se ven sometidos los cuerpos. Pese a ser una aproximación de la realidad, ha demostrado ser capaz de describir con gran precisión movimientos reales de cohetes, moléculas, planetas, etc.

En este tema se explicará que el movimiento es uno de los fenómenos físicos más básicos, consistiendo en un cambio en la posición del cuerpo. Este movimiento hará que el cuerpo describa una trayectoria. El objetivo principal será describir ese movimiento, determinando su posición, velocidad y aceleración en función del tiempo y/o la posición de este.

Estos movimientos se clasificarán en función de su trayectoria (rectilíneo, circular, parabólico, etc.) o por la presencia de aceleración (movimiento rectilíneo uniforme, movimiento rectilíneo uniformemente acelerado, etc.).

## Cinemática 

La cinemática es la parte de la física que se encarga de describir y estudiar los movimientos de los cuerpos sin importar las causas que originan tal movimiento. Los planteamientos de los movimientos estarán caracterizados por una descripción matemática de este. Gran parte de los movimientos quedarán reducidos a una geometría en el espacio tetradimensional, con tres dimensiones espaciales (x, y, z) y una temporal.

Para describir estos movimientos será necesario introducir magnitudes cuya variación temporal nos permitirá describir los movimientos. Podríamos describir con palabras los movimientos y los cambios en las magnitudes, pero sería demasiado laborioso. Se utilizarán herramientas matemáticas para describir estos cambios, de manera que nos permitan analizar, sintetizar y universalizar el lenguaje.

En este tema, realizaremos una primera aproximación que será fundamental: los cuerpos estudiados se considerarán como un punto material. De esta forma, se entiende que las dimensiones del cuerpo sometido a estudio son despreciables con respecto al camino recorrido. Dado que los cuerpos que se van a estudiar son cuerpos rígidos, el punto material coincidirá con el centro de masas del cuerpo. Como este es rígido, guardará una relación constante entre cada punto del objeto y el centro de masas, por lo que se podrá saber la posición de cada parte del objeto real partiendo de la del centro de masas. Esta aproximación no podrá hacerse siempre. En el caso de planetas, por ejemplo, podremos considerarlos cuerpos puntuales al estudiar sus trayectorias en torno al Sol, pero no podremos hacer eso si estudiamos la rotación sobre su eje.

## Elementos para la descripción del movimiento 

La descripción de los movimientos en física clásica suponen la existencia de un espacio euclídeo y de un tiempo absoluto que fluye "a su propio ritmo", independientemente del estado de movimiento del observador.

Toda descripción del movimiento de un cuerpo debe partir del establecimiento de un **sistema de referencia**, es decir, un punto en el espacio que supondremos fijo y en el que se supone que las magnitudes de la posición son nulas y del que partirán unos ejes coordenados. El sistema de referencia vendrá dado por un triedro positivo de coordenadas ligado a ese punto fijo. La **posición** de un cuerpo se denotará como **$\vec{r}$** y será un vector en la base del espacio vectorial del sistema de referencia $(\vec{i}, \vec{j}, \vec{k})$:

$$\vec{r} = x \cdot \vec{i} + y \cdot \vec{j} + z \cdot \vec{k} = (x,y,z)$$

Diremos que un cuerpo está en movimiento si su posición varía con respecto al tiempo. Esta dependencia funcional entre el tiempo y la posición podrá escribirse de forma explícita como:




$$
    \vec{r}(t) = x(t)\vec{i} + y\vec{j} + z\vec{k} = (x(t),y(t),z(t))
$$ {#eq-vec}


La @eq-vec se denomina **ecuación vectorial del movimiento**. Esta expresión nos demuestra que cualquier movimiento puede representarse como una suma de 3 movimientos rectilíneos, perpendiculares entre sí tal que sus trayectorias quedan definidas en cada uno de los ejes cartesianos $x, y, z$. Esto nos permite reducir cualquier movimiento a la forma matemática más sencilla (el movimiento rectilíneo), lo cual es sumamente importante. La @eq-vec puede escribirse de forma escalar utilizando la @eq-pospar, que define en paramétricas la **trayectoria**:

$$
\begin{cases}
  x = x(t)\\
  y = y(t)\\
  z = z(t)
\end{cases}
$$ {#eq-pospar}

También es posible representar la ecuación de la trayectoria eliminando el parámetro $t$. Por ejemplo, para el siguiente movimiento:

$$
    \vec{r}(t) = (2t+5)\cdot\vec{i} + t^2\cdot\vec{j} - 3\cdot\vec{k},
$$
$$
    x = 2t+5 \text{, } y = t^2 \text{, } z = -3,
$$

$$
    \begin{cases}
      z + 3 = 0\\
      x^2 - 10x - 4y + 25 = 0
    \end{cases}
$$ {#eq-pos}

Una de las magnitudes escalares más importantes es el *espacio recorrido*, denotado con la letra *$s$*. La ecuación para obtener el espacio recorrido se llama *ley horaria del movimiento* (@eq-hor)

$$
s = |\vec{r}(t)| = s(t)
$$ {#eq-hor}

La @eq-pos y la @eq-hor nos dan la misma información que la @eq-vec

### Velocidad 

A partir de la @eq-vec podemos definir ciertas magnitudes que nos permitirán definir el movimiento de una forma más directa. Una de estas magnitudes es la *velocidad*.

Suponiendo $t_1 \text{ y } t_2$ dos instantes diferentes, la posición en cada instante vendrá definida por: $\vec{r_1}(t_1)\text{, } \vec{r_2}(t_2)$.

La *velocidad media* media de un móvil quedará definida como:
$$
  \vec{v_m} = \frac{\Delta\vec{r}}{\Delta\vec{t}} = \frac{\vec{r_2}-\vec{r_1}}{t_2-t_1}
$$ {#eq-vm}

Desde un punto de vista físico, esta velocidad representa la variación promedio de la posición en un tiempo dado. No entra en detalle sobre si la velocidad es constante o no, sobre si el cuerpo retrocede en algún momento, etc.

Cuando este intervalo temporal tienda a cero, la velocidad será más representativa del estado actual del cuerpo, de tal forma que si tomamos el límite cuando el intervalo de tiempo tiende a cero, la @eq-vm se convierte en:

$$
  \vec{v} = \lim_{\Delta t \to 0} \frac{\Delta\vec{r}}{\Delta t} = \frac{d\vec{r}(t)}{dt}
$$ {#eq-vi}

Al resultado de este límite lo llamaremos *velocidad instantánea*. Podemos desarrollar esta en función de sus componentes cartesianas:

$$ 
  \vec{v} = v_x\vec{i}+v_y\vec{j}+v_z\vec{k}=\frac{d\vec{r}(t)}{dt}=\frac{dx(t)}{dt}\vec{i}+\frac{dy(t)}{dt}\vec{j}+\frac{dz(t)}{dt}\vec{k}
$$ {#eq-vicartes}

La velocidad en un instante vendrá dada por un vector perpendicular a la trayectoria del cuerpo, en el sentido deo movimiento y  cuyo módulo llamaremos *celeridad* y representaremos con una *c*. La celeridad representa la rapidez con la que el móvil describe la trayectoria

$$
  c=\frac{ds}{dt},
$$ {#eq-cel}

pues, para $\Delta t \to 0$, $\Delta s \to \Delta r$. Además:

$$
  \vec{v} = \frac{d\vec{r}}{dt}=\frac{d\vec{r}}{ds}\cdot\frac{ds}{dt}=\vec{\tau}\cdot\frac{ds}{dt}=c\vec{\tau}
$$

Expresando el vector velocidad referido a un sistema de ejes ligado al punto móvil obtenemos las *componentes intrínsecas* de la velocidad. En dicho sistema de referencia, la celeridad es la única componente intrínseca. En el S.I. la velocidad se mide en m/s y su ecuación dimensional es 

$$
  [v] = [L] \cdot[T]^{-1}
$$

#### Velocidad media

Supongamos un móvil P que ocupa la posición A en el instante $t_1$ y la posición en el instante $t_2$. $\vec{r_1}=\vec{OA}$ y $\vec{r_2}=\vec{OB}$. El vector desplazamiento $\vec{AB}$ se podrá calcular como $\vec{AB} = \vec{OB}-\vec{OA}$, ya que $\vec{OA}+\vec{AB}=\vec{OB}$. Por tanto, $\vec{AB}=\vec{r_2}-\vec{r_1}$. La velocidad media entonces será:

$$
  \vec{v_m}=\frac{\vec{AB}}{t_2-t_1}=\frac{\vec{r_2}-\vec{r_1}}{t_2-t_1}=\frac{\Delta\vec{r}}{\Delta t}
$$

El módulo de $\vec{AB}$ es la celeridad y es una magnitud escalar. En un movimiento rectilíneo, la velocidad media siempre tendría la misma dirección.

En un sistema de coordenadas OXY, con $OA=(x_1,y_1)$ y $OB=(x_2,y_2)$, las componentes del vector $\vec{v_m}$ son:

$$
    (\vec{v_m})_x = \frac{x_2-x_1}{t_2-t_1} = \frac{\Delta x}{\Delta t}
$$
$$
    (\vec{v_m})_y = \frac{y_2-y_1}{t_2-t_1} = \frac{\Delta y}{\Delta t}
$$

Y la celeridad:

$$
  c = |v_m| = \sqrt{(v_m)_x^2+(v_m)_y^2} = \sqrt{(\frac{\Delta x}{\Delta t})^2 + (\frac{\Delta y}{\Delta t})^2}
$$

Si suponemos el cuerpo como un sólido rígido que se desplaza con movimiento de traslación, el vector desplazamiento en un momento dado tiene el mismo módulo, dirección y sentido, por lo que todos tienen la misma velocidad media.

### Aceleración

La aceleración expresa el cambio de la velocidad en el tiempo. Dado que la velocidad es una magnitud vectorial, la aceleración también lo será. La *aceleración media* queda definida como:

$$
  \vec{a_m} = \frac{\Delta\vec{v}}{\Delta t} = \frac{\vec{v_2}-\vec{v_1}}{t_2-t_1} = \frac{\vec{v}(t_2)-\vec{v}(t_1)}{t_2-t_1}
$$ {#eq-am}

La *aceleración instantánea* la definiremos como:

$$
  \vec{a} = \lim_{\Delta t \to 0} \vec{a_m} = \frac{d\vec{v}}{dt} = \frac{d}{dt}( \frac{d\vec{r}}{dt} ) = \frac{d^2\vec{r}}{dt^2}
$$ {#eq-a}

$\vec{a}$ coincide con el ritmo de variación temporal de la velocidad en un instante dado. De igual modo que para la velocidad, la aceleración puede definirse en base a sus *componentes cartesianas* o sus *componentes intrínsecas*.

#### Componentes cartesianas

De la @eq-a se pueden obtener inmediatamente las componentes cartesianas:

$$
  \vec{a} = a_x\vec{i} + a_y\vec{j} + a_z\vec{k} = \frac{dv_x}{dt}\vec{i} + \frac{dv_y}{dt}\vec{j} + \frac{dv_z}{dt}\vec{k} = \frac{d^2x(t)}{dt^2}\vec{i} + \frac{d^2y(t)}{dt^2}\vec{j} + \frac{d^2y(t)}{dt^2}\vec{k}
$$ {#eq-a-carte}

Si trasladamos el origen del vector velocidad al origen de coordenadas, el extremo describirá una curva conocida como \emph{hodógrafa} del movimiento. Observando la posición de la hodógrafa respecto a la trayectoria y la de la aceleración respecto a la hodógrafa, es fácil concluir que el vector aceleración estará situado en el plano que contiene a la hodógrafa y al origen de coordenadas.

#### Componentes intrínsecas

Estas componentes son el resultado de expresar el vector en un referencial situado sobre la trayectoria, con dos componentes: una perpendicular a la trayectoria (normal $\vec{n}$) y otra tangente (tangencial $\vec{\tau}$).

##### Aceleración tangencial {.unnumbered}

La aceleración tangencial es un vector con los siguientes atributos:
- *Módulo*: es igual a la rapidez de cambio del módulo velocidad.
- *Dirección*: es tangente a la trayectoria en todo punto.
- *Sentido*: es el mismo que el del movimiento si el módulo velocidad aumenta y contrario si disminuye.

##### Aceleración normal {.unnumbered}

Esta componente aparece si el movimiento es curvilíneo, así que se genera por los cambios en la dirección de la velocidad, con independencia de lo que le ocurra al módulo. Es perpendicular a la dirección tangente y a la trayectoria. El plano determinado por ambas componentes se denomina *plano osculador*, y su posición varía con el tiempo

Expresando $\vec{v}=v\vec{\tau}$ es fácil obtener las componentes:

$$
  \vec{a} = \frac{d\vec{v}}{dt} = \frac{d(v\vec{\tau})}{dt} = \frac{dv}{dt}\cdot\tau + v\cdot\frac{d\vec{\tau}}{dt}
$$

El primer sumando corresponde con la *componente tangencial* y el segundo sumando corresponde con la *componente normal*.

Calcular la aceleración tangencial es fácil sabiendo la velocidad.

La aceleración normal exige conocer cómo evoluciona el vector unitario tangente:

$$
  \frac{d\vec{\tau}}{dt} = \frac{d\vec{\tau}}{ds}\cdot\frac{ds}{dt}
$$

Realizando un estudio detallado se concluye que la componente *normal* vale:

$$
  a_n = \frac{v^2}{\rho}
$$ {#eq-a-normal}

El módulo de la aceleración es:

$$
  a = \sqrt{a_x^2+a_y^2} = \sqrt{a_t^2+a_n^2}
$$ {#eq-a-modulo}

En el S.I. la aceleración tiene unidades de $m/s^2$ y su ecuación dimensional es $[a] = [L]\cdot[T]^2$

|    $a_n+a_t=0$   |       $a_n=0/a_t=0$      |         Movimiento rectilíneo uniforme (MRU)         |
|:----------------:|:------------------------:|:----------------------------------------------------:|
|   $a_n+a_t=cte$  |      $a_n=0/a_t=cte$     | Movimiento rectilíneo uniformemente acelerado (MRUA) |
|   $a_n+a_t=cte$  |     $a_n=0/a_t\neq 0$    |         Movimiento rectilíneo acelerado (MRA)        |
|   $a_n+a_t=cte$  |     $a_n=cte 0/a_t=0$    |          Movimiento circular uniforme (MCU)          |
|   $a_n+a_t=cte$  |   $a_n = cte/ a_t= cte$  |  Movimiento circular uniformemente acelerado (MCUA)  |
| $a_n + a_t =cte$ | $a_n\neq 0 / a_t \neq 0$ | Movimiento curvilíneo acelerado (MCA)                |


| Magnitud               | Movimiento rectilíneo         | Movimiento circular                                | Relación entre magnitudes |
|------------------------|-------------------------------|----------------------------------------------------|---------------------------|
| Distancia              | $e$                           | $\theta$                                           | $s=\theta\cdot R$         |
| Velocidad              | $v=de/dt$                     | $\omega=d\theta/dt$                                | $v=\omega\cdot R$         |
| Aceleración tangencial | $a_t=dv/dt$                   | $\alpha=d\omega/dt$                                | $a_t=\alpha\cdot R$       |
| Aceleración normal     | $a_n=v^2/R$                   | $a_n=\omega^2\cdot R$                              |                           |
| Posición               | $s=s_0+v_0 t+\frac{1}{2}at^2$ | $\theta=\theta_0+\omega_0 t+\frac{1}{2}\alpha t^2$ | $s=\theta\cdot R$         |
| Velocidad              | $v=v_0+at$                    | $\omega=\omega_0+\alpha t$                         | $v=\omega \cdot R$        |

## Movimientos de especial interés 

Como hemos visto, en todo movimiento hay una relación entre las magnitudes posición, velocidad y aceleración, establecidas mediante el operador derivada. También podemos realizar el camino contrario: conociendo la aceleración y las condiciones de contorno, podemos obtener la velocidad y la posición

### Movimientos rectilíneos

Estos movimientos se caracterizan porque la dirección del vector velocidad no cambia, es decir, $a_n=0$. Dado que la trayectoria es rectilínea, el movimiento puede tratarse únicamente con la distancia al origen, por lo que mayormente se reduce a un tratamiento escalar.

#### Movimiento rectilíneo uniforme (MRU) {.unnumbered}

Es el movimiento de un punto cuyo vector velocidad mantiene el mismo módulo, dirección y sentido. Se definen por la condición $\vec{v}=cte$. Por tanto, integrando $ds=v\cdot dt$:

$$
s=s_0 + v(t-t_0) = s_0 + v\Delta t
$$ {#eq-mru}

Si $t_0$, entonces $s=s_0+vt$.

```{python}
#| label: fig-MRU
#| fig-cap: "s y v vs t en un MRU"

import numpy as np
import matplotlib.pyplot as plt

t = np.arange(0, 5, 0.01)
v = 5 + 0*t
s = v*t
fig, (ax1, ax2) = plt.subplots(1, 2)
fig.suptitle('Gráficas del MRU')
ax1.plot(t, v)
ax2.plot(t, s)
ax1.set(xlabel='t', ylabel='v')
ax2.set(xlabel='t', ylabel='s')
```

#### Movimiento rectilíneo uniformemente acelerado (MRUA)

En este movimiento, $\vec{a_n}=0$ porque es rectilíneo, por lo que $\vec{a}=\vec{a_t}$. Como es uniformemente acelerado, la aceleración será constante durante todo el recorrido $\vec{a}=cte$.

Teniendo en cuenta que $|\vec{a}|=|\vec{a_t}|=\frac{dv}{dt}$, podemos integrar desde $t_0=0$ a $t$, obteniendo así la ecuación de la velocidad:

$$
v = v_0 + at
$$ {#eq-velmrua}

Integrando $ds = v\cdot dt$, obtendremos la ecuación que permite calcular el espacio recorrido:

$$
s = s_0 + v_0t + \frac{1}{2}at^2
$$ {#eq-esmrua}

Con la @eq-velmrua y la @eq-esmrua podemos obtener la ecuación independiente del tiempo:

$$
v^2 - v_0^2 = 2a(s-s_0) = 2a\Delta s
$$ {#eq-mruaindept}

```{python}
#| label: fig-MRUA
#| fig-cap: "s y v vs t en un MRUA"

import numpy as np
import matplotlib.pyplot as plt

t = np.arange(0, 5, 0.01)
a = 1
v0 = 0
s0 = 0
v = v0 + a*t
s = s0 + v0*t + 0.5 * a * (t ** 2)
fig, (ax1, ax2) = plt.subplots(1, 2)
fig.suptitle('Gráficas del MRUA')
ax1.plot(t, v)
ax2.plot(t, s)
ax1.set(xlabel='t', ylabel='v')
ax2.set(xlabel='t', ylabel='s')
```

### Composición de movimientos rectilíneos

En muchos casos, el movimiento de un cuerpo debe descomponerse en movimientos más sencillos para poder analizarlo. En estos casos, se toma como base la *ley clásica de velocidades* $\vec{v}(t) = \vec{v_1}(t) + \vec{v_2}(t)$.

#### Movimiento de proyectiles

En este tipo de movimientos, es posible describir este como
la composición de dos movimientos, un MRU y un MRUA, siempre despreciando el rozamiento con el aire. El primero es consecuencia del mismo lanzamiento y el segundo es consecuencia de la acción gravitatoria.

En función del ángulo que forma el vector velocidad con la horizontal se tienen dos movimientos: *tiro horizontal* y *tiro oblícuo*.

##### Tiro horizontal {.unnumbered}

En este movimiento, tendremos un MRU en el eje horizontal, que llamaremos X, y un MRUA en el eje vertical, que llamaremos Y. El vector velocidad inicial sólo tendrá componente horizontal, es decir $\vec{v_0} = v_0\cdot \vec{i}$. En estos casos, tomaremos la altura de lanzamiento como $y=0$, la posición horizontal desde donde se lanza $x_0=0$, la dirección vertical ascendente como positiva y el sentido del vector velocidad horizontal como positivo. La aceleración de la gravedad $g = -9,81 m/s^2$ se tratará como positiva en el desarrollo de las ecuaciones, ya que el signo está en el propio valor de $g$. De esta forma se generan las siguientes ecuaciones para cada eje:

  - Eje X: $x = v_0\cdot t$
  - Eje Y: $y = 1/2\cdot gt^2$ 
    - $v_y = g\cdot t$

Utilizando las ecuaciones de la posición de los dos ejes obtenemos:

$$
y = \frac{g}{2v_0^2}x^2
$$

Es la *ecuación de la trayectoria* correspondiente a una parábola con vértice en el (0,0). Aplicando la ley de adición de velocidades, la ecuación vectorial de la velocidad será $\vec{v}(t) = v_{0x}\cdot\vec{i} - gt\cdot\vec{j}$.

Siendo su módulo $v(t) = \sqrt{v_{0x}^2+g^2t^2}$.

Su dirección vendrá determinada por: $\theta(t) = \arctan{\frac{-gt}{v_{0x}}}$.

Derivando la velocidad obtenemos que $\vec{a}(t) = -g\cdot\vec{j}$.

::: {.callout-note}
Revisar este planteamiento matemático porque no cuadra.
:::




## Métodos para el estudio experimental del movimiento 
